# Created with Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: YuzuEmu.Yuzu.Mainline
PackageVersion: '1598'
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: yuzu-windows-msvc/yuzu.exe
UpgradeBehavior: install
ReleaseDate: 2023-10-23
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/yuzu-emu/yuzu-mainline/releases/download/mainline-0-1598/yuzu-windows-msvc-20231023-59431af62.zip
  InstallerSha256: 27DAC9A9763FCFD1028D9AC6E609A05795A2A3124402655E77DBCA58C6B6478D
ManifestType: installer
ManifestVersion: 1.5.0
